language: python
sudo: false
install:
  - wget https://raw.githubusercontent.com/google/styleguide/gh-pages/cpplint/cpplint.py
script:
  - python cpplint.py --linelength=120 --extensions=cpp --headers=hpp src/*
