language: python

python: 2.7

sudo: false

services: mysql

addons:
  apt:
    packages:
    - php5-cli

install:
    - pip install pep8
    - wget https://google-styleguide.googlecode.com/svn/trunk/cpplint/cpplint.py

before_script:
    - mysql -uroot < sql/schema.sql

script:
    - php -l scripts/charDump.php
    - pep8 scripts/addDataToDB.py
    - pep8 scripts/basicServer.py
    - python cpplint.py --linelength=120 --extensions=hpp,cpp --filter=-build/c++11,-build/include_order src/*
